## Mod

This application uses `tey/mod` to place generated files in its own layout and to discover its providers, commands, listeners and migrations. Run `php artisan mod:list --json` first to inspect file types, templates, scaffolds and discovery. Before placing a file, check the configured layout, not the package defaults: `'layout'` in `config/mod.php`, any `Mod::layout()` calls in service providers, and the Composer PSR-4 mappings. Prefer the matching `mod:*` generator over `make:*`, and give its placement explicitly: `Knowledge:Document`, `--in=Knowledge`, or the layout's own option such as `--module=Knowledge`. Use the `mod-development` skill when generating files or changing layouts, stubs, base classes or discovery.

After choosing `ddd` or adding a layout root outside `app/`, run `php artisan mod:autoload` to add missing Composer PSR-4 mappings and reload the autoloader. Use `--dry-run` to preview the entries or `--no-dump` when a script runs Composer itself.

Always pass `--no-interaction` and the options that answer required questions. When a class shape repeats, create a generator template with `mod:template <type> <name>` or `mod:template --from=<Class> --into=<path> --no-interaction`. When several file types repeat together, register a scaffold using `->makes()` and sibling aliases. Include `use Tey\Mod\Scaffolds\Scaffold;` in every scaffold example, and `use Tey\Mod\Scaffolds\Part;` when typing a part closure. Inspect the whole plan and choose collision options explicitly. Use `->generates()`, `->mounts()`, `->relates()` and `->excludes()` in layout declarations.

Before writing, run the chosen command with `--dry-run --json`. Read its files, inserts, warnings, and `would_write` flag. The preview writes nothing and emits only JSON; required answers come from flags or defaults. A missing answer appears as a warning with `would_write: false`, even though the preview exits 0. Use `--dry-run` alone for a text table. Each new command or option must be documented in this guideline or the mod-development skill; the package checks coverage in its test suite.
