<?php

use Tey\Mod\Discovery\DiscoveryType;
use Tey\Mod\Discovery\RejectionReason;
use Tey\Mod\Facades\Mod;
use Tey\Mod\Tests\Feature\Acceptance\Support\AcceptanceApp;
use Tey\Mod\Tests\Feature\Acceptance\Support\LayoutUnderTest;

/*
 * Acceptance, layout 1: ordinary Laravel (no placement dimension), the
 * built-in default `laravel` layout plus a custom query kind added from
 * AppServiceProvider::boot().
 * generate -> relate -> reverse-map -> discover -> cache -> replay, through
 * the service provider only, then the negative cases.
 */

function ordinaryLayout(): LayoutUnderTest
{
    return new LayoutUnderTest('laravel', fn () => Mod::layout('laravel')->kind('query', in: 'Queries'));
}

it('runs the whole loop on ordinary Laravel', function () {
    AcceptanceApp::run(ordinaryLayout(), function (AcceptanceApp $app) {
        $t = $app->tag;
        $app->boot();

        // 1. Generate, with relations: model -> factory, controller -> store/update requests.
        $app->artisan('mod:model', ['name' => "Invoice{$t}", '--factory' => true])->assertSuccessful();
        $app->artisan('mod:controller', ['name' => "Invoice{$t}Controller", '--model' => "Invoice{$t}", '--requests' => true])->assertSuccessful();
        $app->artisan('mod:provider', ['name' => "Billing{$t}"])->assertSuccessful();
        $app->artisan('mod:event', ['name' => "Invoice{$t}Paid"])->assertSuccessful();
        $app->artisan('mod:listener', ['name' => "Send{$t}Receipt", '--event' => "Invoice{$t}Paid"])->assertSuccessful();
        $app->artisan('mod:command', ['name' => "Prune{$t}Invoices"])->assertSuccessful();
        // query: a custom kind added from AppServiceProvider::boot().
        $app->artisan('mod:query', ['name' => "Overdue{$t}Invoices"])->assertSuccessful();
        $app->artisan('mod:migration', ['name' => 'create_invoices_table'])->assertSuccessful();

        $migration = $app->migration('database/migrations', 'create_invoices_table');

        $generated = [
            "app/Console/Commands/Prune{$t}Invoices.php" => ['command', "App\\Console\\Commands\\Prune{$t}Invoices"],
            "app/Events/Invoice{$t}Paid.php" => ['event', "App\\Events\\Invoice{$t}Paid"],
            "app/Http/Controllers/Invoice{$t}Controller.php" => ['controller', "App\\Http\\Controllers\\Invoice{$t}Controller"],
            "app/Http/Requests/StoreInvoice{$t}Request.php" => ['request', "App\\Http\\Requests\\StoreInvoice{$t}Request"],
            "app/Http/Requests/UpdateInvoice{$t}Request.php" => ['request', "App\\Http\\Requests\\UpdateInvoice{$t}Request"],
            "app/Listeners/Send{$t}Receipt.php" => ['listener', "App\\Listeners\\Send{$t}Receipt"],
            "app/Models/Invoice{$t}.php" => ['model', "App\\Models\\Invoice{$t}"],
            "app/Providers/Billing{$t}ServiceProvider.php" => ['provider', "App\\Providers\\Billing{$t}ServiceProvider"],
            "app/Queries/Overdue{$t}Invoices.php" => ['query', "App\\Queries\\Overdue{$t}Invoices"],
            "database/factories/Invoice{$t}Factory.php" => ['factory', "Database\\Factories\\Invoice{$t}Factory"],
            $migration => ['migration', null],
        ];
        ksort($generated);

        expect($app->files())->toBe(array_keys($generated));

        // Relations use resolved identities.
        expect($app->read("app/Models/Invoice{$t}.php"))->toContain("HasFactory<\\Database\\Factories\\Invoice{$t}Factory>")
            ->and($app->read("app/Http/Controllers/Invoice{$t}Controller.php"))
            ->toContain("use App\\Http\\Requests\\StoreInvoice{$t}Request;")
            ->toContain("use App\\Http\\Requests\\UpdateInvoice{$t}Request;")
            ->toContain("use App\\Models\\Invoice{$t};")
            ->and($app->read("app/Listeners/Send{$t}Receipt.php"))->toContain("use App\\Events\\Invoice{$t}Paid;");

        // 2. Every generated file maps back to the kind that made it.
        foreach ($generated as $path => [$kind, $fqcn]) {
            $app->assertOwned($path, $kind, [], $fqcn);
        }

        // 3. A hand-written listener, never generated by mod, is owned the same way.
        $hand = $app->handWrite("app/Listeners/Audit{$t}Payment.php", 'App\Listeners', <<<PHP
            use App\\Events\\Invoice{$t}Paid;

            class Audit{$t}Payment
            {
                public function handle(Invoice{$t}Paid \$event): void {}
            }
            PHP);
        $app->assertOwned($hand, 'listener', [], "App\\Listeners\\Audit{$t}Payment");

        // 4. A fresh boot discovers and registers them (cold scan).
        $app->boot();
        $cold = $app->discovery()->inventory();
        $event = "App\\Events\\Invoice{$t}Paid";

        expect($app->discovery()->source())->toBe('scan')
            ->and($cold->classes(DiscoveryType::Provider))->toBe(["App\\Providers\\Billing{$t}ServiceProvider"])
            ->and($cold->classes(DiscoveryType::Command))->toBe(["App\\Console\\Commands\\Prune{$t}Invoices"])
            ->and($cold->classes(DiscoveryType::Listener))->toBe(["App\\Listeners\\Audit{$t}Payment", "App\\Listeners\\Send{$t}Receipt"])
            ->and($cold->rejections)->toBe([]);

        $assertRegistered = function () use ($app, $t, $event) {
            expect($app->app()->getProvider("App\\Providers\\Billing{$t}ServiceProvider"))->not->toBeNull()
                ->and($app->hasArtisanCommand("App\\Console\\Commands\\Prune{$t}Invoices"))->toBeTrue()
                ->and($app->app()->make('events')->getRawListeners()[$event] ?? [])->toEqualCanonicalizing([
                    "App\\Listeners\\Audit{$t}Payment@handle",
                    "App\\Listeners\\Send{$t}Receipt@handle",
                ]);
        };
        $assertRegistered();

        // 5. Cache, then replay on a fresh boot: identical inventory and registrations.
        $app->artisan('mod:cache')->assertSuccessful();
        $app->boot();

        expect($app->discovery()->source())->toBe('cache')
            ->and($app->discovery()->inventory()->toArray())->toBe($cold->toArray());
        $assertRegistered();
    });
});

it('refuses, rejects and reports on ordinary Laravel', function () {
    AcceptanceApp::run(ordinaryLayout(), function (AcceptanceApp $app) {
        $t = $app->tag;
        $app->boot();

        $app->artisan('mod:model', ['name' => "Invoice{$t}"])->assertSuccessful();
        $before = $app->read("app/Models/Invoice{$t}.php");

        // Collision: generating the same artifact again is refused before any write.
        $app->artisan('mod:model', ['name' => "Invoice{$t}"])
            ->expectsOutputToContain('Model already exists.')
            ->assertSuccessful();
        expect($app->read("app/Models/Invoice{$t}.php"))->toBe($before);

        // Unknown file type: the layout declares no handler; mod:handler says which layout has one.
        $app->artisan('mod:handler', ['name' => 'Anything'])
            ->expectsOutputToContain('mod:handler is not a command of the laravel layout. The slices layout has it.')
            ->assertFailed();

        // --in in a layout without dimensions.
        $app->artisan('mod:model', ['name' => "Other{$t}", '--in' => 'Billing'])->assertFailed();
        expect(file_exists($app->root->path("app/Models/Other{$t}.php")))->toBeFalse();

        // Deliberate non-registration: owned by a discovered kind, but not what the type requires.
        $app->handWrite("app/Providers/Helpers{$t}ServiceProvider.php", 'App\Providers', "class Helpers{$t}ServiceProvider {}");
        $app->handWrite("app/Console/Commands/Report{$t}.php", 'App\Console\Commands', "class Report{$t} {}");
        // Not owned: no rule recognises these files.
        $app->handWrite("app/Support/Money{$t}.php", 'App\Support', "class Money{$t} {}");
        $app->handWrite("app/Providers/Nested/Deep{$t}ServiceProvider.php", 'App\Providers\Nested', "class Deep{$t}ServiceProvider extends \\Illuminate\\Support\\ServiceProvider {}");

        $app->boot();
        $inventory = $app->discovery()->inventory();

        expect($inventory->isEmpty())->toBeTrue()
            ->and($inventory->rejection("app/Providers/Helpers{$t}ServiceProvider.php")?->reason)->toBe(RejectionReason::Ineligible)
            ->and($inventory->rejection("app/Console/Commands/Report{$t}.php")?->reason)->toBe(RejectionReason::Ineligible)
            ->and($inventory->rejection("app/Support/Money{$t}.php")?->reason)->toBe(RejectionReason::NotOwned)
            ->and($inventory->rejection("app/Providers/Nested/Deep{$t}ServiceProvider.php")?->reason)->toBe(RejectionReason::NotOwned)
            ->and($app->app()->getProvider("App\\Providers\\Nested\\Deep{$t}ServiceProvider"))->toBeNull()
            ->and($app->hasArtisanCommand("App\\Console\\Commands\\Report{$t}"))->toBeFalse();
    });
});
